name: Check and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.channel }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - toolchain: "1.86"
            features: ""
            channel: "stable"
          - toolchain: "nightly-2025-03-05"
            features: "--features backtrace"
            channel: "nightly"

    steps:
      - uses: actions/checkout@v3
      - name: Override Rust toolchain
        run: rustup override set ${{ matrix.toolchain }}
      - name: Add Rust components
        run: rustup component add rustfmt clippy
      - name: Format
        run: cargo fmt --check
      - name: Build
        run: cargo build  --all-targets ${{ matrix.features }}
      - name: Clippy
        run: cargo clippy ${{ matrix.features }} -- -D warnings
      - name: Run tests
        run: cargo test   --workspace ${{ matrix.features }}
      - name: Generate docs
        run: RUSTDOCFLAGS="-Dwarnings --cfg docsrs" cargo doc --no-deps
